# Generated by Django 5.0.3 on 2024-04-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
